name: Build, Release & Deploy WASM-4 Game

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.15.1'

      - name: Cache Zig build files
        uses: actions/cache@v4
        with:
          path: zig-cache
          key: ${{ runner.os }}-zig-${{ hashFiles('**/*.zig', 'build.zig') }}
          restore-keys: |
            ${{ runner.os }}-zig-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install w4 tools
        run: npm install -g wasm4

      - name: Build and Bundle Game
        shell: bash
        run: |
          mkdir -p release
          zig build --release=small
          w4 bundle \
            --html release/index.html \
            --windows release/game.exe \
            --linux release/game \
            --mac release/game_osx \
            --title "${{ vars.GAME_NAME }}" \
            --description "${{ vars.GAME_DESCRIPTION }}" \
            --timestamp \
            zig-out/bin/cart.wasm
          chmod u+x release/game*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm4-game
          path: release

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: wasm4-game
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_PAT }}
          files: release/*
          generate_release_notes: true

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: wasm4-game
          path: release
      
      - name: Setup butler
        uses: remarkablegames/setup-butler@v2

      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          butler push release/index.html ${{ vars.ITCHIO_USER }}/${{ vars.ITCHIO_GAME }}:html5 --userversion ${{ github.ref_name }}
          butler push release/game.exe ${{ vars.ITCHIO_USER }}/${{ vars.ITCHIO_GAME }}:windows --userversion ${{ github.ref_name }}
          butler push release/game ${{ vars.ITCHIO_USER }}/${{ vars.ITCHIO_GAME }}:linux --userversion ${{ github.ref_name }}
          butler push release/game_osx ${{ vars.ITCHIO_USER }}/${{ vars.ITCHIO_GAME }}:osx --userversion ${{ github.ref_name }}

